Move control track related content in a separate document
ietf-wg-cellar/matroska-specification pull request #461
Opened 2021-03-07 08:46 UTC by robUx4

The new document is in a dirty state and we may never use it. But it's a way to clean the Control Track reference (an under specified and unused feature) out of the main document.

Fixes #456

2021-03-07 17:10 UTC, hubblec4 commented
> move ChapterTrack and ChapterTrackUID in the Control Tracks spec
Is this really only for Control Tracks?

A good player could read the ChapterTrack and uses only the listed tracks (ordered chapters are required).

2021-03-14 08:04 UTC, robUx4 commented
`ChapterTrack` is useless without a `ChapterTrackUID`, because it means "all tracks", just as if it doesn't exist.

It's true that the `ChapterTrackUID` spec currently says
> In the absence of a control track, choosing this chapter will select the listed Tracks and deselect unlisted tracks.

But just like control track it's not currently used so I'd rather move it out for now than delaying the specifications for something noone has ever used. Neither vlc nor libavformat support these elements.

2021-03-14 08:07 UTC, robUx4 commented
BTW, the specs contained as many features as we could think of, even not correctly/properly defined because the idea was to have as much "prior art" as possible. So if anyone tries to patent a new feature they can't because we already thought of it. Even the chapter codecs fall in this category except it got to a proof of concept in VLC.

We don't need these extra parts in the v1 to v4 specs which is meant to specify what is currently used in Matroska.

2021-03-14 16:54 UTC, mbunkus requested changes

2021-03-14 16:54 UTC, mbunkus commented on chapters.md
> +        </ChapterAtom>
This change in indentation is wrong.

2021-03-14 16:54 UTC, mbunkus commented on chapters.md
> +        </ChapterAtom>
This change in indentation is wrong.

2021-03-14 16:54 UTC, mbunkus commented on chapters.md
> +        </ChapterAtom>
This change in indentation is wrong.

2021-03-14 16:54 UTC, mbunkus commented on chapters.md
> +        </ChapterAtom>
This change in indentation is wrong.

2021-03-14 16:54 UTC, mbunkus commented on index_control.md
> +  email="slhomme@matroska.org"
inconsistent indentation (should probably be two spaces for both lines)

2021-03-14 16:54 UTC, mbunkus commented on index_control.md
> + email="moritz@bunkus.org"
inconsistent indentation (should probably be two spaces for both lines)

2021-03-14 16:54 UTC, mbunkus commented on chapters.md
> +set to `true`. The first `Edition` with the `EditionFlagDefault Flag` set to `true`
Is the trailing space here intentional? Trailing spaces are significant for Markdown (two spaces == forced line break),
though this instance looks more like an accident.

2021-03-28 08:17 UTC, robUx4 commented
Rebased after the #342 merge which had more text based on now-moved elements. As a result some tables and text have been simplified.

2021-03-28 08:33 UTC, robUx4 commented
Rebase after #469 merged.

2021-04-11 05:57 UTC, merged