make ChapterDisplay use only one language at a time
ietf-wg-cellar/matroska-specification pull request #514
Opened 2021-05-30 07:09 UTC by robUx4

Following the discussion in https://github.com/ietf-wg-cellar/ebml-specification/issues/409
It could be assumed that English is always present because ChapLanguage is
mandatory and has a default value.

To avoid this interpretation we should have one language (and one IETF variant)
per ChapterDisplay item. We already have to use many ones per language. The merge
of different values because they have the same value is unlikely (but it may
exist in the real world).

2021-05-30 08:03 UTC, robUx4 commented
libavformat doesn't use the element either [when reading](https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/matroskadec.c#L626) and always [writes a single `"und"` value](https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/matroskaenc.c#L1687).

libwebm [reads a single value](https://aomedia.googlesource.com/aom/+/refs/heads/master/third_party/libwebm/mkvparser/mkvparser.cc#3665) (possibly leaking data if more than one value is found) and [writes a single value](https://aomedia.googlesource.com/aom/+/refs/heads/master/third_party/libwebm/mkvmuxer/mkvmuxer.cc#2072).

2021-05-30 11:43 UTC, hubblec4 commented
No this is not a bug and I tottaly disagree with this change.

2021-05-30 17:38 UTC, mbunkus requested changes
I've made my objections known in ietf-wg-cellar/ebml-specification#409 where we should keep the discussion about what to do until we reach consensus, I think.

2021-06-06 07:40 UTC, robUx4 commented
OK with allowing multiple values although some clarifications are needed on the EBML side.

2021-06-06 07:40 UTC, closed without merging