Remove range attribute from element with a (large) restriction section
ietf-wg-cellar/matroska-specification pull request #515
Opened 2021-05-30 07:47 UTC by robUx4

The restriction mentions the value that are allowed. The range gives the lower
and upper limits. But without an indication on what to do with values in the
range but with an unknown value we have more confusion than necessary.

If the restriction values are later expanded older parser will ignore the new
values no matter what. The range is only useful to tell if the value is legit
or not, but there's still plenty of changes it is not.

Somehow fixes the issue raised in https://github.com/ietf-wg-cellar/ebml-specification/issues/410

2021-05-30 12:17 UTC, hubblec4 commented
Yes we should remove the range attribute if a restriction is present.
We have more then these two elements: here a list:
`TrackType`
`FlagInterlaced`: the range matches the restriction but should also removed
'FieldOrder'
`ProjectionType`: the range matches the restriction but should also removed
`ContentEncodingScope`

2021-05-30 13:47 UTC, mbunkus requested changes
I agree that the ranges should go if restrictions exist.

Please extend the patch to cover all such elements. I've looked through `ebml_matroska.xml`, too, and the list by @hubblec4 looks to be complete.

@hubblec4 I've edited your comment slightly for improved formatting only.

2021-06-06 06:47 UTC, robUx4 commented
Done

2021-06-06 11:27 UTC, hubblec4 approved these changes

2021-06-06 15:11 UTC, retokromer approved these changes

2021-06-13 06:56 UTC, merged