exclude Matroska v5 elements from the v4 document
ietf-wg-cellar/matroska-specification pull request #657
Opened 2022-08-07 05:57 UTC by robUx4

So we can start merging v5 elements and they won't affect the v4 document.

v5 elements will likely be part of a new document that may not include elements
from v1 to v4.

2022-08-07 05:58 UTC, robUx4 commented
#318 and #606 could be merged after this MR.

2022-08-14 04:59 UTC, robUx4 commented
Ping @mbunkus I'd like to merge this so I can merge #318, #606 and #659. For the Matroska specs it will be transparent. But on the (de)muxer side that means you may start adding v5 support in you case you encounter those elements.

2022-08-14 05:05 UTC, retokromer approved these changes
LGTM

2022-08-14 12:55 UTC, mbunkus requested changes
As far as I know, [XPath supports `<=`](https://www.w3.org/TR/1999/REC-xpath-19991116/#NT-RelationalExpr), so why not use the [`number` function](https://www.w3.org/TR/1999/REC-xpath-19991116/#function-number) and write this as `and (number(@minver)<=4)` (untested)? It'd be what we actually want to express, isn't it? Or maybe we'd have to handle `minver` not being present, too.

2022-08-15 05:58 UTC, robUx4 commented
Done. We can now have v6, v7, v8, etc and the source will still produce the same v1 to v4 IETF document.

2022-08-21 13:59 UTC, merged